---
title: "R Notebook"
---

```{r setup, include=FALSE, results="hide"}
knitr::opts_chunk$set(echo = FALSE, message = FALSE, results='hide')
library(tidyverse)
library(Hmisc)
library(skimr)
library(naniar)
library(patchwork)
library(plotly)
library(ggplot2)
library(DataExplorer)
library(knitr)
library(reshape2)
library(lubridate)
```


```{r}
knitr::opts_chunk$set(echo = FALSE, message = FALSE, results='hide')
if(!require("PerformanceAnalytics")) install.packages("PerformanceAnalytics")
if(!require("corrplot")) install.packages("corrplot")
```


```{r}
knitr::opts_chunk$set(echo = FALSE, message = FALSE, results='hide')
library(PerformanceAnalytics)
library(corrplot)
```

# leo datos



```{r echo = TRUE}
data<-read.csv("entrena.csv",stringsAsFactors = F)
```
 
 
# dias de la semana


```{r}
fecha = ymd(paste(data$arrival_date_year,data$arrival_date_month,data$arrival_date_day_of_month))

data <- data %>% mutate(dia_sem = wday(fecha))
data <- data %>% mutate(dia_sem = if_else(dia_sem==1, "domingo", as.character(dia_sem)))
data <- data %>% mutate(dia_sem = if_else(dia_sem==2, "lunes", as.character(dia_sem)))
data <- data %>% mutate(dia_sem = if_else(dia_sem==3, "martes", as.character(dia_sem)))
data <- data %>% mutate(dia_sem = if_else(dia_sem==4, "miercoles", as.character(dia_sem)))
data <- data %>% mutate(dia_sem = if_else(dia_sem==5, "jueves", as.character(dia_sem)))
data <- data %>% mutate(dia_sem = if_else(dia_sem==6, "viernes", as.character(dia_sem)))
data <- data %>% mutate(dia_sem = if_else(dia_sem==7, "sabado", as.character(dia_sem)))
```


# pascuas
```{r, echo = FALSE}
pascua <- ymd(as.character(timeDate::Easter(2015:2017)))
pascua_m1 <- ymd(as.character(timeDate::Easter(2015:2017))) - days(1)
pascua_m2 <- ymd(as.character(timeDate::Easter(2015:2017))) - days(2)
pascua_m3 <- ymd(as.character(timeDate::Easter(2015:2017))) - days(3)
pascua_m4 <- ymd(as.character(timeDate::Easter(2015:2017))) - days(4)
pascua_m5 <- ymd(as.character(timeDate::Easter(2015:2017))) - days(5)
pascua_m6 <- ymd(as.character(timeDate::Easter(2015:2017))) - days(6)

data <- data %>% mutate(fecha = fecha)
data$pascua <- as.numeric(data$fecha %in% pascua)
data$pascua_m1 <- as.numeric(data$fecha %in% pascua_m1)
data$pascua_m2 <- as.numeric(data$fecha %in% pascua_m2)
data$pascua_m3 <- as.numeric(data$fecha %in% pascua_m3)
data$pascua_m4 <- as.numeric(data$fecha %in% pascua_m4)
data$pascua_m5 <- as.numeric(data$fecha %in% pascua_m5)
data$pascua_m6 <- as.numeric(data$fecha %in% pascua_m6)
data<- data %>% mutate(semana_santa = pascua + pascua_m1 +
                                      pascua_m2 + pascua_m3 + pascua_m4 + pascua_m5 + 
                         pascua_m6)
```

 
 
# Creo las 3 bases
```{r echo = TRUE, results='hide'}
knitr::opts_chunk$set( message = FALSE, results='hide')
idx <- sample(seq(1, 3), size = nrow(data), replace = TRUE, prob = c(.7, 2, .1))
train <- data[idx == 1,]
test <- data[idx == 2,]
cal <- data[idx == 3,]

```


```{r}

cancelados <- subset(train, is_canceled == "cancelado")
```


```{r}
cuenta <- cancelados %>% group_by(fecha) %>% count(is_canceled) 
```


```{r}
agrupados <- tibble(cuenta)
```




```{r}
ggplot(agrupados, aes(x = fecha, y=n))+
geom_point() +
  geom_smooth(method = "loess", span = 0.5, method.args = list(degree = 1), se = FALSE)
```


```{r}
mod_1 <- loess(n ~ as.numeric(fecha), data = agrupados, span = 0.5, degree = 1)
agrupados <- agrupados %>% mutate(ajuste_1 = fitted(mod_1)) %>%
    mutate(res_1 = n - ajuste_1)
```

```{r}
mod_anual <- loess(res_1 ~ as.numeric(fecha), data = agrupados, degree = 1, span = 0.1)
agrupados <- agrupados %>% mutate(ajuste_2 = fitted(mod_anual)) %>%
    mutate(res_2 = res_1 - ajuste_2)
```

```{r, echo = FALSE, fig.height=2.5, echo = FALSE,  out.width = '90%', fig.align= 'center', cache=TRUE, fig.asp = 0.35}
ggplot(agrupados, aes(x = fecha)) +
    geom_point(aes(y = res_1), alpha = 0.2, size = 1) +
    geom_line(aes(y = ajuste_2), colour = "red", size = 1.2)
```


```{r}

agrupados <- agrupados %>% mutate(dia_sem = wday(fecha))
agrupados <- agrupados %>% mutate(dia_sem = if_else(dia_sem==1, "domingo", as.character(dia_sem)))
agrupados <- agrupados %>% mutate(dia_sem = if_else(dia_sem==2, "lunes", as.character(dia_sem)))
agrupados <- agrupados %>% mutate(dia_sem = if_else(dia_sem==3, "martes", as.character(dia_sem)))
agrupados <- agrupados %>% mutate(dia_sem = if_else(dia_sem==4, "miercoles", as.character(dia_sem)))
agrupados <- agrupados %>% mutate(dia_sem = if_else(dia_sem==5, "jueves", as.character(dia_sem)))
agrupados <- agrupados %>% mutate(dia_sem = if_else(dia_sem==6, "viernes", as.character(dia_sem)))
agrupados <- agrupados %>% mutate(dia_sem = if_else(dia_sem==7, "sabado", as.character(dia_sem)))
```

```{r}
agrupados <- agrupados %>%
    group_by(dia_sem) %>%
    nest() %>%
    mutate(ajuste_mod =
      map(data, ~ loess(res_2 ~ as.numeric(fecha), data = .x, span = 0.1, degree = 1))) %>%
    mutate(ajuste_3 =  map(ajuste_mod, fitted)) %>%
    select(-ajuste_mod) %>% unnest(cols = c(data, ajuste_3)) %>%
    mutate(res_3 = res_2 - ajuste_3) %>% ungroup
```

```{r, echo = FALSE, fig.height=3, echo = FALSE,  out.width = '90%', fig.align= 'center', cache=TRUE, fig.asp = 0.35}
ggplot(agrupados, aes(x = fecha)) +
    geom_point(aes(y = res_2), alpha = 0.5, colour = "gray") +
    geom_line(aes(y = ajuste_3, colour = dia_sem), size = 1) +
    xlab("")
```



```{r, fig.height=2.5, echo = FALSE,  out.width = '90%', fig.align= 'center', cache=TRUE, fig.asp = 0.35}
ggplot(agrupados, aes(x = fecha, y = res_3)) +
    geom_line() +
    geom_smooth(method = "loess", span = 0.02,
                method.args = list(degree=1, family = "symmetric"))
```


```{r, echo = FALSE, fig.height=3, echo = FALSE,  out.width = '90%', fig.align= 'center', cache=TRUE, fig.asp = 0.35}
ggplot(agrupados, aes(sample = res_3)) +
  geom_qq(distribution = stats::qunif) +
  ylab("cancelaciones (residual)") + xlab("")
```


```{r}
datos_dia <-  agrupados
```




```{r}
# Quitamos componente anual y efecto de día de la semana
datos_dia <- datos_dia %>% mutate(n_1 = n - ajuste_2 - ajuste_3)
# Reajustamos
mod_1 <- loess(n_1 ~ as.numeric(fecha), data = datos_dia, span = 0.02, degree = 2,
               family = "symmetric")
```

```{r, echo = FALSE,fig.height=3, echo = FALSE,  out.width = '90%', fig.align= 'center', cache=TRUE, fig.asp = 0.35}
datos_dia <- datos_dia %>% ungroup %>%
    mutate(ajuste_4 = fitted(mod_1)) %>%
    mutate(res_4 = n - ajuste_4) %>%
    mutate(n_2 = n - ajuste_4 - ajuste_3)
ggplot(datos_dia, aes(x = fecha)) +
    geom_point(aes(y = n_1), alpha = 0.3, size = 1) +
    geom_line(aes(y = ajuste_4), colour = "red", size = 1)
```


```{r, fig.height=3, echo = FALSE,  out.width = '90%', fig.align= 'center', cache=TRUE, fig.asp = 0.35}
mod_anual <- loess(n_2 ~ as.numeric(fecha), data = datos_dia,
               degree = 2,  span = 0.01, family = "symmetric")
datos_dia <- datos_dia %>%
    mutate(ajuste_5 = fitted(mod_anual)) %>%
    mutate(res_5 = n_2 - ajuste_5) %>%
    mutate(n_3 = n - ajuste_4 - ajuste_5)
```

```{r, echo = FALSE, fig.height=3, echo = FALSE,  out.width = '90%', fig.align= 'center', cache=TRUE, fig.asp = 0.35}
ggplot(datos_dia, aes(x = fecha)) +
    geom_point(aes(y = n_2), alpha = 0.2, size = 1) +
    geom_line(aes(y = ajuste_5), colour = "red", size = 1)
```

Y ahora repetimos con la componente de día de la semana:

```{r, echo = FALSE, fig.height=3, echo = FALSE,  out.width = '90%', fig.align= 'center', cache=TRUE, fig.asp = 0.35}
datos_dia <- datos_dia %>% group_by(dia_sem) %>% nest() %>%
    mutate(ajuste_mod = map(data, ~ loess(n_3 ~ as.numeric(fecha), data = .x, span = 0.1,
                                          degree=1, family = "symmetric"))) %>%
    mutate(ajuste_6 =  map(ajuste_mod, fitted)) %>%
    select(-ajuste_mod) %>%
    unnest(cols = c(data, ajuste_6)) %>%
    mutate(res_6 = n_3 - ajuste_6)
ggplot(datos_dia, aes(x = fecha, y = n_3, group = dia_sem)) +
  geom_point(aes(y = n_3), alpha = 0.2, size = 1)  +
    geom_line(aes(y = ajuste_6, colour = dia_sem), size =1)
```

### Análisis de componentes {-}

Ahora comparamos las componentes estimadas y los residuales en una misma
gráfica. Por definición, la suma de todas estas componentes da los datos
originales.

```{r, fig.width =7, fig.height = 7, cache = TRUE, echo = FALSE,  out.width = '90%', fig.align= 'center'}
media <- mean(datos_dia$n) %>% round
datos_l <- datos_dia %>%
    select(fecha, dia_sem, n, ajuste_4, ajuste_5, ajuste_6, res_6) %>%
    mutate(ajuste_4_centrado = ajuste_4 - mean(ajuste_4)) %>%
    gather(componente, valor, ajuste_5:ajuste_4_centrado) %>%
    mutate(componente = recode(componente, ajuste_4_centrado="Tendencia", ajuste_5 = "Anual", ajuste_6 = "Día de la semana",
                               res_6 = "Residual")) %>%
    mutate(componente = fct_relevel(componente, "Tendencia", "Anual", "Día de la semana", "Residual"))
ggplot(datos_l, aes(x = fecha, y = valor, colour = dia_sem)) +
    facet_wrap(~ componente,  ncol = 1) +
    geom_point(size=0.5) + 
    labs(caption = "Media total: 6435")

```
